// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqpbnrvnnymwsvlpdndj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGJucnZubnltd3N2bHBkbmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Nzk4NzgsImV4cCI6MjA2MDU1NTg3OH0.8BNnxlQGNhCeDXExOOJou_J8D5u9WI-NOsXMmLJgUwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);